<a href="https://colab.research.google.com/github/justiceakodia/ADS-Assignment-2-3/blob/main/PhD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [2]:

%%time
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
np.random.seed(42)

CPU times: user 451 ms, sys: 181 ms, total: 632 ms
Wall time: 1.08 s

In [6]:
import tensorflow as tf
from tensorflow import keras
import keras
from keras import Sequential, Model
from keras.layers import Dense,Input,Activation

In [7]:
CDT=pd.read_excel('/content/drive/MyDrive/PhD Project/Data/CDT8.xlsx')

In [8]:
CDT.isnull().sum()

Transaction_ID           0
RISK_LEVEL               0
CONTAINER_SIZE_CODE      0
IS_REEFER                0
CLEARING_AGENCY_CODE     0
LAST_PORT                0
BL_VERSION               0
BOE_VERSION              0
CARRIERCODE              0
CNEE_CODE                0
DEC_CODE                 0
DLV_GDS_LOC_CODE         0
EXAM_STATUS              0
IMP_CODE                 0
MANIFESTED_WEIGHT        0
REGIME                   0
HZ_STATUS                0
SHIP_AGENT_CODE          0
LINE_CODE                0
NEXT_PORT                0
POL                      0
BERTH_REQUEST            0
BL_TYPE                  0
ADDITIONAL               0
AGENT_OPERATIVE_ID_NO    0
DWELL_DAYS               0
dtype: int64

In [9]:
CDT.shape

(307597, 26)

In [10]:
CDT.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307597 entries, 0 to 307596
Data columns (total 26 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Transaction_ID         307597 non-null  int64
 1   RISK_LEVEL             307597 non-null  object
 2   CONTAINER_SIZE_CODE    307597 non-null  object
 3   IS_REEFER              307597 non-null  int64
 4   CLEARING_AGENCY_CODE   307597 non-null  object
 5   LAST_PORT              307597 non-null  object
 6   BL_VERSION             307597 non-null  int64
 7   BOE_VERSION            307597 non-null  int64
 8   CARRIERCODE            307597 non-null  object
 9   CNEE_CODE              307597 non-null  object
 10  DEC_CODE               307597 non-null  object
 11  DLV_GDS_LOC_CODE       307597 non-null  object
 12  EXAM_STATUS            307597 non-null  object
 13  IMP_CODE               307597 non-null  object
 14  MANIFESTED_WEIGHT      307597 non-null  float64
 15  REGIME                 307597 non-null  object
 16  HZ_STATUS              307597 non-null  int64
 17  SHIP_AGENT_CODE        307597 non-null  object
 18  LINE_CODE              307597 non-null  object
 19  NEXT_PORT              307597 non-null  object
 20  POL                    307597 non-null  object
 21  BERTH_REQUEST          307597 non-null  object
 22  BL_TYPE                307597 non-null  object
 23  ADDITIONAL             307597 non-null  int64
 24  AGENT_OPERATIVE_ID_NO  307597 non-null  object
 25  DWELL_DAYS             307597 non-null  float64
dtypes: float64(2), int64(6), object(18)
memory usage: 61.0+ MB

In [11]:
CDT.head()

   Transaction_ID RISK_LEVEL  ... AGENT_OPERATIVE_ID_NO  DWELL_DAYS
0           69915        RED  ...               AA17613    3.970833
1          254625        RED  ...               AA12692   20.011111
2           48039       BLUE  ...                AA0215    2.893750
3           75395     YELLOW  ...                AA2268    4.139583
4          204257     YELLOW  ...               AA19007   13.062500

[5 rows x 26 columns]

In [12]:
target = pd.DataFrame(CDT[["DWELL_DAYS"]])

In [13]:
target

        DWELL_DAYS
0         3.970833
1        20.011111
2         2.893750
3         4.139583
4        13.062500
...            ...
307592   10.986111
307593    9.840278
307594   82.506944
307595   69.649306
307596  189.738194

[307597 rows x 1 columns]

In [14]:
x_categorical=CDT.drop(columns=["DWELL_DAYS","Transaction_ID","MANIFESTED_WEIGHT","CNEE_CODE","IMP_CODE","AGENT_OPERATIVE_ID_NO","IS_REEFER","BL_VERSION","BOE_VERSION","HZ_STATUS","ADDITIONAL"])

In [15]:
x_categorical.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307597 entries, 0 to 307596
Data columns (total 15 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   RISK_LEVEL            307597 non-null  object
 1   CONTAINER_SIZE_CODE   307597 non-null  object
 2   CLEARING_AGENCY_CODE  307597 non-null  object
 3   LAST_PORT             307597 non-null  object
 4   CARRIERCODE           307597 non-null  object
 5   DEC_CODE              307597 non-null  object
 6   DLV_GDS_LOC_CODE      307597 non-null  object
 7   EXAM_STATUS           307597 non-null  object
 8   REGIME                307597 non-null  object
 9   SHIP_AGENT_CODE       307597 non-null  object
 10  LINE_CODE             307597 non-null  object
 11  NEXT_PORT             307597 non-null  object
 12  POL                   307597 non-null  object
 13  BERTH_REQUEST         307597 non-null  object
 14  BL_TYPE               307597 non-null  object
dtypes: object(15)
memory usage: 35.2+ MB

In [16]:
dummied_cat=pd.get_dummies(x_categorical)

In [17]:
dummied_cat

        RISK_LEVEL_BLUE  RISK_LEVEL_GREEN  ...  BL_TYPE_House Bl  BL_TYPE_Master
0                     0                 0  ...                 0               1
1                     0                 0  ...                 0               1
2                     1                 0  ...                 0               1
3                     0                 0  ...                 0               1
4                     0                 0  ...                 0               1
...                 ...               ...  ...               ...             ...
307592                0                 1  ...                 0               1
307593                0                 0  ...                 0               1
307594                0                 0  ...                 0               1
307595                0                 0  ...                 0               0
307596                0                 0  ...                 0               1

[307597 rows x 1751 columns]

In [18]:
#x_categorical.CNEE_CODE.value_counts().to_dict()

In [19]:
x_numeric=CDT[["MANIFESTED_WEIGHT","IS_REEFER","BL_VERSION","BOE_VERSION","HZ_STATUS","ADDITIONAL"]]
x_numeric

        MANIFESTED_WEIGHT  IS_REEFER  ...  HZ_STATUS  ADDITIONAL
0                 4480.00          0  ...          0           0
1                 5000.00          0  ...          0           0
2                 2154.00          0  ...          0           0
3                26978.56          0  ...          0           0
4                17320.00          0  ...          0           0
...                   ...        ...  ...        ...         ...
307592           40339.00          0  ...          0           0
307593            8405.00          1  ...          0           0
307594           10835.00          0  ...          0           0
307595           23000.00          0  ...          0           0
307596           20000.00          0  ...          0           0

[307597 rows x 6 columns]

In [20]:
scaling=StandardScaler()
scaled_x_numeric_Manifested=scaling.fit_transform(target)

In [21]:
scaled_x_numeric_Manifested=pd.DataFrame(data=x_numeric,columns=["MANIFESTED_WEIGHT"])
scaled_x_numeric_Manifested

        MANIFESTED_WEIGHT
0                 4480.00
1                 5000.00
2                 2154.00
3                26978.56
4                17320.00
...                   ...
307592           40339.00
307593            8405.00
307594           10835.00
307595           23000.00
307596           20000.00

[307597 rows x 1 columns]

In [22]:
x_non_scaled= x_numeric.drop(columns=["MANIFESTED_WEIGHT"])
x_non_scaled

        IS_REEFER  BL_VERSION  BOE_VERSION  HZ_STATUS  ADDITIONAL
0               0           1            0          0           0
1               0           1            1          0           0
2               0           1            1          0           0
3               0           1            0          0           0
4               0           1            0          0           0
...           ...         ...          ...        ...         ...
307592          0           1            0          0           0
307593          1           1            0          0           0
307594          0           1            0          0           0
307595          0           2            1          0           0
307596          0           1            0          0           0

[307597 rows x 5 columns]

In [23]:
frames = [scaled_x_numeric_Manifested,dummied_cat,x_non_scaled,target]
combined=pd.concat(frames,axis=1)
combined

        MANIFESTED_WEIGHT  RISK_LEVEL_BLUE  ...  ADDITIONAL  DWELL_DAYS
0                 4480.00                0  ...           0    3.970833
1                 5000.00                0  ...           0   20.011111
2                 2154.00                1  ...           0    2.893750
3                26978.56                0  ...           0    4.139583
4                17320.00                0  ...           0   13.062500
...                   ...              ...  ...         ...         ...
307592           40339.00                0  ...           0   10.986111
307593            8405.00                0  ...           0    9.840278
307594           10835.00                0  ...           0   82.506944
307595           23000.00                0  ...           0   69.649306
307596           20000.00                0  ...           0  189.738194

[307597 rows x 1758 columns]

In [24]:
X=combined.drop(columns=["DWELL_DAYS"])
y=combined["DWELL_DAYS"]

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [26]:
##model=RandomForestRegressor()

In [27]:
#model.fit(X_train,y_train)

In [51]:
model=Sequential()

model.add(Dense(10, activation='relu', input_dim = X.shape[1]))
model.add(Dense(10, activation='relu'))
model.add(Dense(10, activation="relu"))
model.add(Dense(10, activation="relu"))
model.add(Dense(10, activation="relu"))

model.add(Dense(1, activation = 'sigmoid'))
model.compile(optimizer='RMSprop', loss = 'mse',metrics=['accuracy'])

In [29]:

%%timeit
model.fit(X_train, y_train, batch_size = 20, epochs = 10, verbose = 1,validation_data=(X_test,y_test))

Epoch 1/10
12304/12304 [==============================] - 28s 2ms/step - loss: 362.1567 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 2/10
12304/12304 [==============================] - 26s 2ms/step - loss: 362.1111 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 3/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1126 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 4/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1118 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 5/10
12304/12304 [==============================] - 28s 2ms/step - loss: 362.1125 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 6/10
12304/12304 [==============================] - 28s 2ms/step - loss: 362.1118 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 7/10
12304/12304 [==============================] - 30s 2ms/step - loss: 362.1129 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 8/10
12304/12304 [==============================] - 28s 2ms/step - loss: 362.1123 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 9/10
12304/12304 [==============================] - 28s 2ms/step - loss: 362.1108 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 10/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1122 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 1/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1113 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 2/10
12304/12304 [==============================] - 28s 2ms/step - loss: 362.1120 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 3/10
12304/12304 [==============================] - 27s 2ms/step - loss: 362.1112 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 4/10
12304/12304 [==============================] - 27s 2ms/step - loss: 362.1126 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 5/10
12304/12304 [==============================] - 28s 2ms/step - loss: 362.1115 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 6/10
12304/12304 [==============================] - 27s 2ms/step - loss: 362.1111 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 7/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1113 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 8/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1119 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 9/10
12304/12304 [==============================] - 30s 2ms/step - loss: 362.1125 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 10/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1117 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 1/10
12304/12304 [==============================] - 32s 3ms/step - loss: 362.1116 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 2/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1117 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 3/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1116 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 4/10
12304/12304 [==============================] - 28s 2ms/step - loss: 362.1117 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 5/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1113 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 6/10
12304/12304 [==============================] - 30s 2ms/step - loss: 362.1110 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 7/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1108 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 8/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1115 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 9/10
12304/12304 [==============================] - 27s 2ms/step - loss: 362.1112 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 10/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1111 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 1/10
12304/12304 [==============================] - 31s 2ms/step - loss: 362.1124 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 2/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1124 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 3/10
12304/12304 [==============================] - 27s 2ms/step - loss: 362.1122 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 4/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1111 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 5/10
12304/12304 [==============================] - 27s 2ms/step - loss: 362.1118 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 6/10
12304/12304 [==============================] - 27s 2ms/step - loss: 362.1111 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 7/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1121 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 8/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1101 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 9/10
12304/12304 [==============================] - 30s 2ms/step - loss: 362.1115 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 10/10
12304/12304 [==============================] - 27s 2ms/step - loss: 362.1123 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 1/10
12304/12304 [==============================] - 30s 2ms/step - loss: 362.1113 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 2/10
12304/12304 [==============================] - 28s 2ms/step - loss: 362.1120 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 3/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1111 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 4/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1121 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 5/10
12304/12304 [==============================] - 27s 2ms/step - loss: 362.1119 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 6/10
12304/12304 [==============================] - 27s 2ms/step - loss: 362.1116 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 7/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1112 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 8/10
12304/12304 [==============================] - 27s 2ms/step - loss: 362.1118 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 9/10
12304/12304 [==============================] - 28s 2ms/step - loss: 362.1122 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 10/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1114 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 1/10
12304/12304 [==============================] - 31s 3ms/step - loss: 362.1116 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 2/10
12304/12304 [==============================] - 27s 2ms/step - loss: 362.1116 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 3/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1115 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 4/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1097 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 5/10
12304/12304 [==============================] - 27s 2ms/step - loss: 362.1126 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 6/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1115 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 7/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1110 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 8/10
12304/12304 [==============================] - 29s 2ms/step - loss: 362.1107 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 9/10
12304/12304 [==============================] - 27s 2ms/step - loss: 362.1123 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
Epoch 10/10
12304/12304 [==============================] - 31s 3ms/step - loss: 362.1113 - accuracy: 6.9084e-05 - val_loss: 336.4847 - val_accuracy: 9.7529e-05
1 loop, best of 5: 4min 55s per loop

In [47]:
# evaluate the model
scores = model.evaluate(X, y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

9613/9613 [==============================] - 19s 2ms/step - loss: 356.9868 - accuracy: 7.4773e-05

accuracy: 0.01%

In [59]:
!pip3 install graphviz
import graphviz

Requirement already satisfied: graphviz in /usr/local/lib/python3.7/dist-packages (0.10.1)

In [53]:
!pip3 install ann_visualizer

Requirement already satisfied: ann_visualizer in /usr/local/lib/python3.7/dist-packages (2.5)

In [54]:
import ann_visualizer as ann_viz

In [61]:
ann_viz(model, view=True, filename = "network.gv")

TypeError: ignored